### ISSUE TITLE
Miscellaneous fixes to align with openapi-common

### ISSUE THREAD

**Issue by Andy-Grigg** [ansys/grantami-bomanalytics#63]
A number of issues were flagged with openapi-common during a code review. We should make those changes here as well:

- [ ] [Add a null handler to the logger](https://github.com/pyansys/openapi-common/issues/67)
- [ ] [Ensure CI stages are named appropriately](https://github.com/pyansys/openapi-common/issues/62)
- [ ] [Pin tox-gh-actions package version](https://github.com/pyansys/openapi-common/issues/51)
